name: Lint & Prettier Check

on:
  pull_request:
    branches: [main, staging]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.md'

jobs:
  lint-and-prettier:
    name: Run Prettier & ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier check
        run: pnpm prettier:check
        continue-on-error: false

      - name: Run ESLint
        run: pnpm lint
        continue-on-error: false
