name: Auto PR with AI Review

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Auto PR from main push'
          branch: 'auto-pr-${{ github.sha }}'
          title: '${{ github.event.head_commit.message }}'
          body: 'This PR was automatically created from a push to main.'

  lint-and-review:
    runs-on: ubuntu-latest
    needs: create-pr
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install deps
      - name: Install dependencies
        run: npm install

      # Run Prettier check
      - name: Prettier check
        run: npx prettier --check .

      # Run ESLint check
      - name: ESLint check
        run: npx eslint .

      # Run AI Code Review
      - name: Run AI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          DIFF=$(git diff HEAD~1 HEAD)
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "{
              \"model\": \"gpt-4o-mini\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"You are a senior code reviewer. Review code for bugs, style, security, and performance issues.\"},
                {\"role\": \"user\", \"content\": \"Review this diff:\n$DIFF\"}
              ]
            }" | jq -r '.choices[0].message.content')

          echo "AI Review Output:"
          echo "$RESPONSE"

          gh pr comment ${{ github.event.pull_request.number }} --body "$RESPONSE"
        continue-on-error: true
